# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lyrical_Banana' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PMSuperButton'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher'
  pod 'SwiftGifOrigin', '~> 1.7.0'

  # Pods for Lyrical_Banana

end
